<?php 

  echo $this->fieldset("home",$this->formButton("recrutement","Recrutement",array("onclick"=>"location.href='../../Recrutement'","style"=>""))

.   $this->formButton("evaluation","Ré évaluation des compétences",array("onclick"=>"location.href='../../Evalcompetence'","style"=>"margin-left:30px;"))


.   $this->formButton("impression","Impressions",array("onclick"=>"location.href='../index/impression'","style"=>"float:right"))


.   $this->formButton("integration","Integration",array("onclick"=>"location.href='../../Integration'","style"=>"clear:both;float:left;"))

 
.   $this->formButton("entretien","Entretien Professionnel",array("onclick"=>"location.href='../../entretien'","style"=>"margin-left:30px;margin-top:20px;"))
 

.   $this->formButton("formation","Formation",array("onclick"=>"location.href='../../Formation'","style"=>"clear:both;margin-top:20px;"))
.   $this->formButton("habilitation","Habilitations",array("onclick"=>"location.href='../../Habilitation'","style"=>"clear:both;"))
 
.    $this->formButton("alerte","Alertes",array("onclick"=>"location.href='../index/alerte'","style"=>"float:right")),array());
 
 
 
 ?>
