<img src="img/logo_login.png" style='float:left;'/>
    <?php
echo $this->fieldset("login","<span style='background-color:#990000;display:block;font-style:italic;'>".$this->message.'</span>'.$this->form,
    array("legend"=>"Connexion",
        "style"=>"width:300px;height:auto;margin-left:-100px;;margin-top:250px;border-radius:15px;float:left;"));
?>
<span id="Version">RHLabo version-<?php echo $this->RHLabo_version;?> </span>
