 <?php
                echo $this->render("header.phtml");
 echo  $this->formButton("BtnDoc","Ajouter un document",array("onclick"=>"","style"=>""));

                ?>
<br/>
Recrutement : Liste des documents  
<br/>
<table><tr>
        <th>Nom</th>
        <th></th>
    </tr>
    <tr>
        <td>Fiche de recrutement</td>
        <td><img src='/img/page_white_acrobat.png'/></td>
            
    </tr></table>