 <?php
                echo $this->render("header.phtml");
 echo  $this->formButton("BtnDoc","Ajouter un recrutement",array("onclick"=>"location.href='./add'","style"=>""));
                ?>

<br/>
Liste des recrutements 
<br/>
<table><tr>
        <th>Poste</th>
        <th>Liste des candidats</th>
        <th>Date d'embauche prévue</th>
        <th>Formation à prévoir</th>
    </tr>
    <tr>
        <td>Technicien</td>
        <td>FRANCOIS Ludovic<br/>
            PRUNIER Stéphane<br/>
            LIEGARD Aurélie</td>
        <td>01/09/2016</td>
        <td>Utilisation logiciel</td>
            
    </tr></table>