<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
  <head>

    <?php echo $this->headMeta(); ?>

    <?php echo $this->headTitle(); ?>

    <?php
     $this->headLink()->prependStylesheet($this->BaseUrl("/css/style.css"));
    $this->headLink(array('rel'=>'favicon', 'href'=>$this->BaseUrl("favicon.ico")), 'PREPEND');
    echo $this->headLink();
    ?>
    <?php echo $this->headScript(); ?>

  </head>

  <body>
    <div id="ca_id" class="container_all">
      <div class="line">
        <div class="header">
          <h1>
            <a href="./"> <img src="<?php echo $this->BaseUrl("images/logo.png"); ?>" id="logo" style='background-color: #ffffff;height: 100px;'/>
            <img alt="Conciergerie citoyenne (logo merci oscar )" src="<?php echo $this->Baseurl("/images/Logo_Conciergerie_merci_oscar.jpg"); ?>" style='height: 100px;' />
  </a>
          </h1>
          <div class="menu user_menu">

          </div>
          <div class="menu main_menu">

          </div>
        </div>

        <div id="contain" class='content' >
          <div id="message"><?php echo $this->message; ?></div>
          <?php echo $this->layout()->content; ?>

        </div>
      </div>
    </div>
     <?php echo $this->InlineScript(); ?>
  </body>

 
</html>