<?php 

  echo $this->fieldset("home",$this->formButton("accueil","Accueil",array("onclick"=>"location.href='../index/Accueil'","style"=>""))
          
         . $this->formButton("acces","Accès",array("onclick"=>"location.href=location.href+'/Acces'","style"=>"margin-left:20px;"))

.  $this->formButton("documents","Documents",array("onclick"=>"location.href=location.href+'/Document'","style"=>"margin-left:20px;"))

.  $this->formButton("gestion","Gestion",array("onclick"=>"location.href=location.href+'/Utilisation'","style"=>"margin-left:20px;"))
 
.  $this->formButton("impression","Impressions",array("onclick"=>"location.href=location.href+'/impression'","style"=>"margin-left:20px;"))
.  $this->formButton("historique","Historique",array("onclick"=>"location.href=location.href+'/Historique'","style"=>"margin-left:20px;"))
.  $this->formButton("alerte","Alertes",array("onclick"=>"location.href='../index/alerte'","style"=>"float:right")),array());
 
 
 
 ?>
