 <?php
                echo $this->render("header.phtml");
 
                ?>
Formation : Gestion des Acces<?php
echo $this->formButton("add","Ajouter un acces",array("onclick"=>"location.href='/".$this->controller."/formacces'","style"=>"margin-left:20px;"));
 
?><br/>
Formation : Liste des autorisations  
<br/>
<table><tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>gestion des accès</th>
        <th>Document</th>
        <th>Gestion</th>
        <th>Impression</th>
        <th>Historique</th>
        <th>Alerte</th>
    </tr>
    <tr>
        <td>Coppée</td>
        <td>Pascal</td>
        <td>Oui</td>
        <td>Oui</td>
        <td>Oui</td>
        <td>Oui</td>
        <td>Oui</td>
        <td>Oui</td>
            
    </tr></table>